### ISSUE TITLE
preliminary installation notes

### ISSUE THREAD

**Issue by kaiiam** [hurwitzlab/planet-microbe-functional-annotation#1]
@kyclark  Here were my notes for getting the pipeline working on a jetstream atmosphere linux vm:

added
```
export PATH=~/software/FragGeneScan1.3:$PATH
export PATH=~/software/Trimmomatic-0.39:$PATH
export PATH=~/software/my_interproscan/interproscan-5.44-79.0:$PATH
export PATH=~/software/pear-0.9.11-linux-x86_64/bin:$PATH
export PATH=~/software/vsearch-2.14.2:$PATH
```
to .bashrc on my atmosphere VM and did `source .bashrc` to always add them. 

Run with: `python3 pipeline/pipeline.py -c ./data/configs/config.txt`

I had to make the following change: in the pipeline.py to get it to run:

`self.trim_executable_fp = os.environ.get('TRIMMOMATIC-0.39.JAR', default='/home/u29/mattmiller899/Trimmomatic-0.39/trimmomatic-0.39.jar')` the default to: `~/software/Trimmomatic-0.39/trimmomatic-0.39.jar`

**Comment by kaiiam** [comment]
@kyclark the [get_test_data.sh](https://github.com/hurwitzlab/planet-microbe-functional-annotation/blob/master/test_data/get_test_data.sh) script has commands for the test data, but all you really need are these two:

```
#OSD illumina example (lower bound) test data
curl -O ftp.sra.ebi.ac.uk/vol1/fastq/ERR771/ERR771001/ERR771001_1.fastq.gz
curl -O ftp.sra.ebi.ac.uk/vol1/fastq/ERR771/ERR771001/ERR771001_2.fastq.gz
```

**Comment by kaiiam** [comment]
@mattmiller899 We should update the TRIMMOMATIC default location, not to be hard coded to your path. Perhaps we can add that to the config file or as an argument or something?

**Comment by kyclark** [comment]
I've built a Docker container on lytic if anyone would like to try it. Here's how to get a shell into the container:

$ sudo docker run -it hurwitzlab/funcadelic:0.1.0 bash

Or run it:

$ sudo docker run hurwitzlab/funcadelic:0.1.0
usage: pipeline.py [-h] -c CONFIG

optional arguments:
  -h, --help            show this help message and exit
  -c CONFIG, --config CONFIG
                        path to config file containing parameters/arguments

In the "data" dir, I added a Makefile to put the test data there.

Here's how you might run it passing the config file pointing to the test data:

$ make run
sudo docker run -v `cd ../data && pwd`:/data hurwitzlab/funcadelic:0.1.0 pipeline.py -c /data/configs/docker.txt
WARNING:utils:directory "/data/out_454/step_01_trimming" already exists
INFO:step_01_trimming:input files = ['/data/in_454/ERR771001_1.fastq.gz', '/data/in_454/ERR771001_2.fastq.gz']
INFO:step_01_trimming:writing output of /data/in_454/ERR771001_1.fastq.gz to /data/out_454/step_01_trimming/ERR771001_1.fastq.gz
INFO:utils:executing "java -jar /home/u29/mattmiller899/Trimmomatic-0.39/trimmomatic-0.39.jar SE -threads 4 -trimlog /data/out_454/step_01_trimming/trim_log /data/in_454/ERR771001_1.fastq.gz /data/out_454/step_01_trimming/ERR771001_1.fastq.gz ILLUMINACLIP:/data/configs/TruSeq3-PE.fa:2:30:10:2:keepBothReads LEADING:3 TRAILING:3 MINLEN:36"
INFO:utils:CompletedProcess(args=['java', '-jar', '/home/u29/mattmiller899/Trimmomatic-0.39/trimmomatic-0.39.jar', 'SE', '-threads', '4', '-trimlog', '/data/out_454/step_01_trimming/trim_log', '/data/in_454/ERR771001_1.fastq.gz', '/data/out_454/step_01_trimming/ERR771001_1.fastq.gz', 'ILLUMINACLIP:/data/configs/TruSeq3-PE.fa:2:30:10:2:keepBothReads', 'LEADING:3', 'TRAILING:3', 'MINLEN:36'], returncode=1)
ERROR:step_01_trimming:Less than 10% (0.0%) of reads survived after Trimmomatic trimming for /data/in_454/ERR771001_1.fastq.gz... Exiting
make: *** [run] Error 1

So there's still some debugging to do, but it's a start with getting all the parts working together.

Is this enough to get the ball rolling? Can you take it from here, or do I need to do more?

Ken

**Comment by kaiiam** [comment]
cc @aponsero  @bhurwitz33 

docker version of [docker-samtools-bowtie2-tophat](https://github.com/johnworth/docker-samtools-bowtie2-tophat)

@mattmiller899 scripts to move datastore using i command and run bowtie to have new version of the datasets run through bowtie. Plan in December: fix up pipelines, make dir on hurwitz lab account we can all access, list of files. Jan start processing data.
